### ISSUE TITLE
plot pseudo-section of phasetensor with tipper

### ISSUE THREAD

**Issue by kashkoulimohammad** [MTgeophysics/mtpy-v2#14]
Hi,
I am tiring to plot pseudo-section of phasetensor with tipper but I faced with this error:
`Traceback (most recent call last):
  File "C:\Users\97627.ICIOC\Desktop\MTpy_V2\2.py", line 10, in <module>
    dgh_mt_data = mc.to_mt_data()
                  ^^^^^^^^^^^^^^^
  File "C:\Users\97627.ICIOC\.conda\envs\MTpy-v2\Lib\site-packages\mtpy\core\mt_collection.py", line 368, in to_mt_data
    for row in self.dataframe.itertuples():
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'itertuples'`

my script is:
`from mtpy import MTCollection
mc = MTCollection()
mc.open_collection(r'C:\Users\Mohammad\Desktop\work\nasrabad_data\nasrabad_data\15\15.h5')

# plot station locations
#station_locations = mc.plot_stations()
#plot_strike_all = mc.plot_strike()

mc.working_dataframe = mc.master_dataframe[mc.master_dataframe.station.str.startswith("SR2")]
dgh_mt_data = mc.to_mt_data()
plot_pt_pseudosection = dgh_mt_data.plot_phase_tensor_pseudosection( 
    plot_tipper="yri", 
    profile_reverse=False,
    y_limits=(10**2, 1)
)`

**Comment by kujaku11** [comment]
@kashkoulimohammad 

Looks like you found a bug.  I'll fix that in the mean time, your code is close, just need to set the `utm_crs` in the `MTData` object instead of the `MTCollection` object:

```
from mtpy import MTCollection
mc = MTCollection()
mc.open_collection(r'C:\Users\Mohammad\Desktop\work\nasrabad_data\nasrabad_data\15\15.h5')
#plot_strike_all = mc.plot_strike()
mc.utm_crs = 32640
mc.working_dataframe = mc.master_dataframe[mc.master_dataframe.station.str.startswith("15_010-0000")]
dgh_mt_data = mc.to_mt_data()
dgh_mt_data.utm_crs = 32640
plot_pt_pseudosection = dgh_mt_data.plot_phase_tensor_pseudosection( 
    plot_tipper="yri", 
    profile_reverse=False,
    y_limits=(10**2, 1)
)
```

**Comment by kashkoulimohammad** [comment]
Thanks @kujaku11 
It does not work.
```
Traceback (most recent call last):
  File "C:\Users\Mohammad\Desktop\MTpy_V2\2_1.py", line 8, in <module>
    dgh_mt_data = mc.to_mt_data(utm_crs=32640)
TypeError: to_mt_data() got an unexpected keyword argument 'utm_crs'
```

**Comment by kujaku11** [comment]
@kashkoulimohammad Try to reinstall mtpy-v2 from git.
